apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:

  volumes:
  - name: shared-data
    emptyDir: { }
  initContainers:
  - name: init-nginx
    image: ansible_initial:local
    volumeMounts:
    - name: shared-data
      mountPath: /etc/nginx
    env:
    - name: SERVICE_A_ENABLED
      value: "True"
    - name: SERVICE_A
      value: "service_a"
    - name: SERVICE_A_IP
      value: "127.0.0.1"
    - name: SERVICE_A_PORT
      value: "8080"
    - name: SERVICE_A_SCHEMA
      value: "http"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /etc/nginx
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
