apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:

  volumes:
  - name: shared-data
    emptyDir: { }
  initContainers:
  - name: init-nginx
    image: initial:local
    volumeMounts:
    - name: shared-data
      mountPath: /etc/nginx
    env:
    - name: SERVICE_A_ENABLED
      value: "True"
    - name: SERVICE_B_ENABLED
      value: "True"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /etc/nginx
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: servcie
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
